AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow SSH and HTTP
      VpcId: vpc-0b4bc09e8cabfa126  # Replace with your VPC ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0b72821e2f351e396  # Replace with the desired AMI ID
      KeyName: jaeEC2                 # Replace with your key pair name
      SecurityGroupIds:
        - !Ref MySecurityGroup
      SubnetId: subnet-0e12a2175faa8a6dd  # Replace with your subnet ID
      Tags:
        - Key: Name
          Value: CircleCI-Instance
