version: 2.1

executors:
  aws-cli-executor:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/repo
    environment:
      AWS_DEFAULT_REGION: "us-east-1"

jobs:
  build-and-deploy:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          name: Run Maven Verify
          command: mvn verify
      - run:
          name: List Target Directory
          command: ls -la target
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
      - setup_remote_docker:
          version: default
      - run:
          name: Build Docker Image
          command: |
            docker build -t to-do-service:latest .
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
      - run:
          name: Delete Existing CloudFormation Stack
          command: |
            aws cloudformation delete-stack --stack-name my-ec2-stack
            aws cloudformation wait stack-delete-complete --stack-name my-ec2-stack
      - run:
          name: Deploy CloudFormation Stack
          command: |
            aws cloudformation deploy \
              --template-file ec2-instance.yaml \
              --stack-name my-ec2-stack \
              --capabilities CAPABILITY_NAMED_IAM
      - run:
          name: Get EC2 Public DNS
          command: |
            INSTANCE_ID=$(aws cloudformation describe-stack-resources --stack-name my-ec2-stack --query "StackResources[?LogicalResourceId=='MyEC2Instance'].PhysicalResourceId" --output text)
            PUBLIC_DNS=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].PublicDnsName" --output text)
            echo "EC2 Public DNS: $PUBLIC_DNS"
            echo "PUBLIC_DNS=$PUBLIC_DNS" >> $BASH_ENV
      - add_ssh_keys:
          fingerprints:
            - "f2:f4:62:26:9d:18:37:39:f4:e0:83:50:05:eb:33:96:71:b4:76:b8"  # Replace with your actual SSH key fingerprint
      - run:
          name: Wait for EC2 to be ready
          command: |
            echo "Waiting for EC2 instance to be ready..."
            sleep 15
      - run:
          name: Install Docker and Docker Compose on EC2
          command: |
            ssh -o StrictHostKeyChecking=no ec2-user@$PUBLIC_DNS "sudo yum update -y && sudo amazon-linux-extras install docker -y && sudo service docker start && sudo usermod -a -G docker ec2-user && sudo curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose"
      - run:
          name: Deploy Java Application using Docker Compose
          command: |
            scp -o StrictHostKeyChecking=no docker-compose.yml ec2-user@$PUBLIC_DNS:~/docker-compose.yml
            scp -o StrictHostKeyChecking=no target/toDoService-0.0.1-SNAPSHOT.jar ec2-user@$PUBLIC_DNS:~/target/toDoService-0.0.1-SNAPSHOT.jar
            ssh -o StrictHostKeyChecking=no ec2-user@$PUBLIC_DNS "docker-compose -f ~/docker-compose.yml up -d"

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy
